language: python
services:
  - docker

stages:
  - name: build docker image
  - name: build clouformation repo
    if: branch = main 
  - name: deploy to aws
    if: branch = main
  
env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pip install -U pip
  - pip install awscli

jobs:
  include:
    - stage: build docker image
      name: "build docker image"
      script:
        - docker build -t pavan0604/nginx:latest .
        - docker images
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push pavan0604/nginx:latest

    - stage: build clouformation repo
      name: "build clouformation repo"
      script:
        - ./cfstack diff --manifest prod.manifest.json --values configuration/values.json --role $AWS_CLOUDFORMATION_SERVICE_IAM_ROLE
        - cat diff.json
        - aws s3 cp diff.json s3://testbucketforcloudflare/travisci/$TRAVIS_BUILD_NUMBER/diff.json

    - stage: deploy to aws
      name: "Deploy to AWS cloudformation"
      script:
        - aws s3 cp s3://testbucketforcloudflare/travisci/$TRAVIS_BUILD_NUMBER/diff.json ./diff.json
        - ./cfstack deploy --manifest diff.json --values configuration/values.json --role $AWS_CLOUDFORMATION_SERVICE_IAM_ROLE